[package]
name = "pecho"
version = "0.1.0"
authors = ["Yuto Nishida <starptr@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = "2.33.3"
lazy_static = "1.4.0"
regex = "1"
