name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    container: "ubuntu:20.04"
    steps:
    - name: "set APT to non-interactive"
      shell: bash
      run: "echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections"
    - name: "Update APT"
      shell: bash
      run: "apt-get update"
    - name: "Install git"
      shell: bash
      run: "apt-get install -y git"
    - name: "Install curl"
      shell: bash
      run: "apt-get install -y curl"
      #- name: "Update APT"
      #  shell: bash
      #  run: "apt-get update"
      #- name: "Install dependencies"
      #  run: |
      #    apt-get install -y cmake pkg-config libfreetype6-dev libfontconfig1-dev \
      #      libxcb-xfixes0-dev python3
    - name: "checkout repo"
      uses: actions/checkout@v2
    - name: "Install stable toolchain"
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: "build binary"
      run: cargo build --release
    - name: "Upload"
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./target/release/pecho
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
